### ISSUE TITLE
AsyncStorage.getItem() doesn't seem to work

### ISSUE THREAD

**Issue by cpojer** [react-native-community/react-native-async-storage#12] opened 2019-02-15 14:45 UTC
* * *
  This issue was originally created by @mrded as facebook/react-native#18372.
  * * *

  

When I try to set a value via `AsyncStorage.getItem()`, I cannot request it back.

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.8.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0

### Expected Behavior

    await AsyncStorage.setItem('foo', 'bar');
    await AsyncStorage.getItem('foo').then(console.log); // 'bar'
    await AsyncStorage.getAllKeys().then(console.log); // ['foo']

### Actual Behavior

    await AsyncStorage.setItem('foo', 'bar');
    await AsyncStorage.getItem('foo').then(console.log); // null
    await AsyncStorage.getAllKeys().then(console.log); // []

### Steps to Reproduce

    import { AsyncStorage } from 'react-native';

    it('should be able to request a value after it was set', async () => {
      await AsyncStorage.setItem('foo', 'bar');
      const output = await AsyncStorage.getItem('foo');

      expect(output).toBe('bar');
    });

    it('should be able to see a new key after a value was set', async () => {
      await AsyncStorage.setItem('foo', 'bar');
      const output = await AsyncStorage.getAllKeys();

      expect(output).toContain('foo');
    });

**Comment by joshjhargreaves** [comment] 2019-02-27 15:51
We recently saw issues with this in our app on a large number of android devices when doing something very similar to the above in production but we had reproducing locally. Very happy to help do the work necessary to fix this. Would be great to use this thread to maybe identify what's causing the issue and different approaches we could use to fix it!

**Comment by retyui** [comment] 2019-03-11 09:32
Maybe an author get null because use of mock implementation:
https://github.com/facebook/react-native/blob/f741d338406d518c4f81fada723991b2938b8cc5/jest/setup.js#L77-L92

**Comment by Krizzu** [comment] 2019-03-11 10:47
Hey @joshjhargreaves 	@retyui 	

Thanks for your time. 
To dig deeper into the issue, I think we'd need more info about reproducing it - from repro steps, it seems like the problem is happening in a test environment (like @retyui pointed out).

Does the issue exist while developing the app?

**Comment by Viswa-Vinod** [comment] 2019-03-13 05:05
did you check whether in Settings --> Apps & notifications-->Permissions-->Storage the app was listed and enabled?

**Comment by mccordgh** [comment] 2019-03-21 20:01
I have the same issue, but found a way to make it work with `.then()`.

We have a separate helper class called `StorageHelper` that has some methods for getting and setting like:
```
// StorageHelper.js

async function set(key, value) {
  try {
    await AsyncStorage.setItem(key, JSON.stringify(value));
  } catch (error) {
    console.error(error);
    return false;
  }

  return true;
};

async function get(key) {
  try {
    const value = await AsyncStorage.getItem(key);

    return JSON.parse(value);
  } catch (error) {
    console.error(error);
    return null;
  }
};

...

setToken(token) {
    return set('token', token);
},

getToken() {
    return get('token');
},

...
```

These were working just fine by utilizing them like this:
`const token = await Storage.getToken();`
and
`Storage.setToken(token);`

Then, I added a new one. I followed the exact same patterns, just changing the name and all of a sudden this same way of getting the value for this `newOne` is returning either a `Promise` or `null` when I try:
` const newOne = await Storage.getNewOne();`

The only way I was able to get the value for `newOne` and use it in my component was:
```
constructor(props) {
    super(props);

    this.state = {
      newOne: null,
    };
  }

  componentDidMount() {
    this.setNewOneFromStorage();
  }

  setNewOneFromStorage = () => {
    Storage.getNewOne().then((newOne) => {
      this.setState({ newOne });
    });
  }
```

Not as ideal, but hope it may help someone.

**Comment by Krizzu** [comment] 2019-04-07 08:57
Right,

I believe the original issue came from the fact that there was no Jest mocking function that would actually get values back.

https://github.com/react-native-community/react-native-async-storage/pull/53 Is PR to help test such cases.


@mccordgh Hey,

This looks odd. Could you provide how you implemented `getNewOne` ?


thanks.

**Comment by mccordgh** [comment] 2019-04-08 14:39
@Krizzu Sorry that may have been confusing to use `newOne` instead of just using `token`.

I edited the previous post to change `newOne` to `token`, as the implementation would have been the same as the `getToken` and `setToken` methods in `StorageHelper.js` above.

**Comment by Krizzu** [comment] 2019-04-11 05:31
v1.3.0 released, please check it out 🙏

**Comment by royisch** [comment] 2019-04-11 06:05
@Krizzu - i still see that the data is not saved after reload. super weird. it used to work fine through the react-native repository. How do you suggest to proceed?

**Comment by royisch** [comment] 2019-04-11 06:17
@Krizzu - i still see a reload issue - after reload the storage is not set anymore and returns null. any suggestions?

**Comment by Krizzu** [comment] 2019-04-11 07:11
@royisch hey,

Can you elaborate bit more? Is in within tests?

**Comment by royisch** [comment] 2019-04-11 08:45
yes. I set using asyncStorage.set, for testing purposes i verified that the data is persisted, so i fetch it back - all looks good. When i reload the same key i get null. 
In general for my use-case - you authenticate and go in. when you reload you see the login screen again.

My question is - should i revert to react-native implementation for now? as my application is waiting to be released.

**Comment by Krizzu** [comment] 2019-04-11 10:16
@royisch 
There's no such API as `asyncStorage.set`. Can you show me some code?

Also, did you clean packager's cache, reinstalled the app/linked module properly?

**Comment by royisch** [comment] 2019-04-11 10:48
Hi @Krizzu i mean `await asyncStorage.setItem`. i will try to clear cache and report back

**Comment by royisch** [comment] 2019-04-11 11:07
hi @Krizzu i cleaned the cache also.

Im using RN 0.59 and installed `"@react-native-community/async-storage": "^1.3.0",`

Not sure what the next step is here. Thanks

**Comment by Krizzu** [comment] 2019-04-11 13:47
@royisch 
Can you show me the code you use?

Additional steps to consider:

1. Run packager with cleaned cached: add `--resetCache` flag when starting
2. Link it: `react-native link @react-native-community/async-storage`
3. Reinstall app: `react-native run-android` or `react-native run-ios`

Or remove `node_modules` and start over

**Comment by royisch** [comment] 2019-04-14 09:03
Hi @Krizzu, did all of it, not sure what the next step is. I will try to completely re-install the library again. 
Also, to notice, im using redux-persist (offline support) , it is also using asyncStorage, maybe something there collides

**Comment by Krizzu** [comment] 2019-04-14 17:20
@royisch I believe that something in your implementation is causing to (maybe) override values in Async Storage (or calling `.clear` in startup.).

I'm closing this issue, if you'll need more help, please open new issue with provided repro steps.


thanks.

**Closed by Krizzu** 2019-04-14 17:20 UTC
Labels: Bug

**Comment by npedrini** [comment] 2019-04-17 08:55
For what it's worth, I'm seeing similar behavior, where a value I set is null upon refreshing the app. I'm also using `redux-offline`, which uses `redux-persist` underneath the hood. I'm wondering if there is some kind of collision when both this newer version of the package and the older one are used at the same time.

**Comment by royisch** [comment] 2019-04-17 10:00
@npedrini - i think i have a solution, you can pass as a configuration to redux-offline the storage you want to use, probably you should import the storage from the new AsyncStorage and pass it as a parameter.

**Comment by never00miss** [comment] 2019-05-14 11:29
@royisch what you mean by new AsyncStorage? From 'react-native' or from '@react-native-community/async-storage'? 

My case is same as @nepedrini,  after apps reload or close, their is doesn't have data back and returned null

**Comment by peterdev6** [comment] 2019-05-16 16:04
@never00miss I can confirm that passing `AsyncStorage` as a param to redux-offline's `persistOptions` solved this issue. You can take a look at [redux-persist config](https://github.com/rt2zz/redux-persist/tree/v4#persiststorestore-config-callback)

**Comment by willdady** [comment] 2019-07-10 00:59
I get a similar issue as @npedrini above. I also use redux-persist and I recently reverted it to using the RN version as I was having issues with this library not correctly rehydrating the state. I was also using _this_ library in a separate part of the code and noticed it was always returning null. Reverting that code to use the RN core version also fixed the issue. 

I've just tried updating all occurrences of AsyncStorage to the RNC version 1.5.1 and it seems to be working now.

**Comment by Krizzu** [comment] 2019-07-10 07:05
@willdady 	
[Please refer to my comment here regarding using both Comm and RN version in the same project](https://github.com/react-native-community/async-storage/issues/118#issuecomment-500138053)

**Comment by willdady** [comment] 2019-07-10 23:54
Actually 1.5.1 does not fix the issue. I'll be reverting to using AsyncStorage from RN core.

**Comment by MakhouT** [comment] 2019-07-30 12:49
Having the same issue. Why is this closed? I am on react-native version 0.59.10 and on version 1.5.1 of asynch storage

**Comment by eightyfive** [comment] 2019-08-01 07:33
@MakhouT https://github.com/facebook/react-native/issues/18372#issuecomment-462214891 might help (if you have control over the AsyncStorage code in your project).

> the solution (at least for me) is: **not to use await in setItem**.

**Comment by Krizzu** [comment] 2019-08-01 07:53
@willdady 	@MakhouT 	Can you tell me more about issues you see?

**Comment by MakhouT** [comment] 2019-08-01 08:28
Investigated a bit more, and the issue isn't async-storage issue. It was react-native-debugger that doesn't instantly show the result when saving an item. I had to refresh the app to see the item in the debugger. Works as expected currently. 
Thanks and sorry for the confusion!

**Comment by jounii** [comment] 2019-08-09 09:36
Just a bit related or unrelated, I was investigating similar problem. The await was hanging at the AsyncStorage. However debugging more, revealed it was hanging on any Promise at application startup. ASyncStorage just seemed to be one of the first during init.

Now the problem was then narrowed down to completely different package (in this case it was @storybook/react-native). Reason for the hang is still mystery, but I suspect it is related somehow incompatible React Native versions being used in two different packages and causing some strange internal conflict which does not show up other than hanging Promises.

Lesson learned, make sure packages are compatible. Also some init code should be run after the React Native has initialized itself, so either use useEffect in your App component or use AppRegistry to time the initialization code instead of running it in the import file's root.

**Comment by jckw** [comment] 2019-08-28 16:47
I'm still encountering this issue.

I set a token after logging in, and can access it after it's been set:

```
async function setToken(token) {
  await AsyncStorage.setItem(AppConfig.TOKEN_STORAGE_KEY, token)
  
  const t = await AsyncStorage.getItem(AppConfig.TOKEN_STORAGE_KEY)
  console.log(t)
}
```

After reloading the app, `await AsyncStorage.getItem(AppConfig.TOKEN_STORAGE_KEY)` returns `null`. 

Not using `await` in the setToken function also doesn't help.

I'm using React Native v0.59.5 and @react-native-community/async-storage v1.3.3.

**Comment by Krizzu** [comment] 2019-08-29 07:45
@Cellule @jckw 	Can you see a yellow box warning about `AsyncStorage` being deprecated? If yes, then there's a condition race happening between Community's and Core `AsyncStorage`.

They're working on the same files/preferences and the way they do might cause the issue you have. [Please refer to my comment about it in another issue](https://github.com/react-native-community/async-storage/issues/118#issuecomment-500138053).

**Comment by jckw** [comment] 2019-08-29 11:03
Ah amazing! Had to patch a few packages we're using that used the old version of AsyncStorage, but now that warning it gone and it seems to have solved the issue.

Thank you!

**Comment by b3hz4d** [comment] 2019-09-19 16:59
I found solution for this
Use this link https://github.com/react-native-community/async-storage/blob/LEGACY/docs/advanced/DedicatedExecutor.md

**Comment by EdwardMcConnell** [comment] 2020-09-16 20:47
On Android, I had the issue where `AsyncStorage.setItem` and `getItem` worked within the same emulator load, but reloading from the dev menu on the emulator resulted in `null` answers for all storage data. This fix worked for me. Add `AsyncStorage_dedicatedExecutor=true` to `android/gradle.properties` and rebuild.

Updated link: [https://react-native-community.github.io/async-storage/docs/advanced/executor](https://react-native-community.github.io/async-storage/docs/advanced/executor)

**Comment by amirping** [comment] 2020-12-11 20:45
I have the same issue in production for some android device, it looks odd that it works on some and on others not.
