### ISSUE TITLE
Undefined is not an object (evaluating 'RCTAsyncStorage.multiMerge')

### ISSUE THREAD

**Issue by cpojer** [react-native-community/react-native-async-storage#14] opened 2019-02-15 14:47 UTC
* * *
  This issue was originally created by @boreales as facebook/react-native#22556.
  * * *

  
  - [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 463.56 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.5.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 27
        Build Tools: 27.0.3
        System Images: android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1

## Description
<img src="https://imgur.com/xjR2E6N.png" alt="image" style="max-width:100%;">

## Reproducible Demo
```
// Store/configureStore.js

import { createStore } from 'redux'
import toggleFavorite from './reducers/favoriteReducer'
import setAvatar from './reducers/avatarReducer'
import { persistCombineReducers } from 'redux-persist'
import storage from 'redux-persist/lib/storage'

const rootPersistConfig = {
  key: 'root',
  storage: storage
}

export default createStore(persistCombineReducers(rootPersistConfig, {toggleFavorite, setAvatar}))
```

The problem seems to be the same as [#21948](https://github.com/facebook/react-native/issues/21948) but I have last react-native version and can't fix it anyway. Any idea ?

**Comment by Maels1991** [comment] 2019-02-18 09:33
Hello,

Same issue here for me.

1. Expo init ... Use Yarn to manage dependencies.
2. In App.js -> componentDidMount -> Using AsyncStorage to store "foo", "bar".
3. Before ejecting using expo, I commit so that I get a clean tree and I create index.js with RegisterComponent ...
4. Ejecting to a Regular React Native Project... -> Ejected successfully! 
5. react-native link -> FIRST ERROR -> "Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'"
6. yarn add @babel/runtime
7. react-native link OK
8. react-native run-ios (waiting ...) -> SECOND ERROR -> "Failed to install the requested application" ... "Print: Entry, ":CFBundleIdentifier", Does Not Exist"
9. Re-run ... fingers crossed : Everything fine ! After building, the app is launched and  I got "undefined is not an object (evaluating 'RCTAsyncStorage.multimerge')"

**Comment by Krizzu** [comment] 2019-02-26 10:58
Hey @Maels1991 @boreales,

It's happening [because of this code here](https://github.com/react-native-community/react-native-async-storage/blob/master/lib/AsyncStorage.js#L347-L351). I'd have to dig deeper to find which native versions do not support merging, so I'd get back to you.

For now, I can suggest checking if `multiMerge` / `mergeItem` is available to avoid crashes.

**Comment by immortalx** [comment] 2019-03-13 01:32
In react-native 0.59 this happens only in android for me, ios runs fine.

**Comment by Krizzu** [comment] 2019-03-13 07:05
Hi @immortalx,

Can you post repro steps? This could help us with nailing down the problem.

**Comment by ynaveed** [comment] 2019-03-13 20:01
Hi, on react-native 0.54, this is also happening on iOS. Worked fined before ejecting. Now it's the above mentioned error.

**Comment by EduVencovsky** [comment] 2019-03-13 20:43
In react-native 0.59, this happens in android even if you don't use `mergeItem` or `multiMerge`

**Comment by dimun** [comment] 2019-03-13 21:37
Same is happening to me, on react-native 0.59.0

**Comment by Krizzu** [comment] 2019-03-14 07:55
Hi @ynaveed 	@EduVencovsky 	@dimun 	

Turns out, it was a issue that slip through when we've changed names in iOS module, due to some problems with case-sensitive naming. 

[Version 1.2.1](https://github.com/react-native-community/react-native-async-storage/releases/tag/v1.2.1) is released, so please check if it's working for you.


Sorry for inconvenience.

**Comment by v0lume** [comment] 2019-03-14 10:47
1.2.1 not working on android

**Comment by Krizzu** [comment] 2019-03-14 15:28
@v0lume 	
I just initialized new project and used version 1.2.1.

Android is working fine for me.
Do you have anything that could help me track this down? Android version / device model / React Native Version used?

**Comment by dimun** [comment] 2019-03-14 15:54
1.2.1 is still not working for android.
I'm testing on two different versions

API 24 with Android 7.0
API 28 with Android 9.0

react-native: 0.59.0
react: 16.8.3
react-native-cli: 2.0.1

**Comment by tsvetan-ganev** [comment] 2019-03-15 18:07
I had the same issue after migrating an app to 0.59.0 and importing this package instead of the one bundled with react-native core. It worked fine on iOS - no crashes and the async storage seemed to function normally (probably it used the version bundled with RN somehow) but crashed on Android with this error. 

The problem was that I forgot to link the module:
```bash
./node_modules/.bin/react-native link @react-native-community/async-storage
```

**Comment by JeffreyHyer** [comment] 2019-03-15 18:24
Had this same issue on Android after upgrading to v0.59.1 (from v0.58.6).

Forgot to run `react-native link @react-native-commmunity/async-storage` which fixed the issue. It's not immediately apparent because (I'm assuming) there's an older version still bundled with react-native core that compiles so the compiler doesn't complain that the native module isn't found.

Thanks @tsvetan-ganev for pointing us in the right direction.

**Comment by Krizzu** [comment] 2019-03-15 20:01
@tsvetan-ganev 	@JeffreyHyer 	Great you have this sorted.
[There's Link instruction README](https://github.com/react-native-community/react-native-async-storage#getting-started), I think I could make it more visible.

**Comment by immortalx** [comment] 2019-03-15 21:23
@Krizzu sorry i could not reproduce outside my own project. Indeed i forgot to run  react-native link as @JeffreyHyer said.
In my case,  the link command did not add new AsyncStoragePackage() to  MainApplication.java so i had to do it manually and now it's working fine in Android and IOS.

**Comment by RWOverdijk** [comment] 2019-04-01 14:00
I did run link and I'm still seeing this. I'm simply using setItem and getItem, nothing fancy.

**Comment by EduVencovsky** [comment] 2019-04-04 20:56
Just Updated to 1.2.2 and I'm getting no error, but nothing works. If I just switch the import back to 'react-native' , everything works fine.
I'm using react-native 0.59 on android.

**Comment by Krizzu** [comment] 2019-04-07 08:51
Hey @EduVencovsky 

Can you elaborate more on `nothing works` ?

**Comment by EduVencovsky** [comment] 2019-04-08 01:28
@Krizzu Sorry it was my mistake, on version 1.2.2, everything is working as expected.

**Comment by Krizzu** [comment] 2019-04-08 05:28
@EduVencovsky I see, glad you got it working.


Closing this one for now, please re-open/create new issue if this would happen again.


thanks.

**Closed by Krizzu** 2019-04-08 05:28 UTC
Labels: Bug

**Comment by joselara-bit** [comment] 2021-03-21 19:08
Here's how to use the correct method for importing.

import AsyncStorage from '@react-native-community/async-storage';
This module is not exported as a react-native, so it must not have a square bracket.

Use in react-native module

import { AsyncStorage } from 'react-native';

**Comment by Krizzu** [comment] 2021-03-21 21:15
`react-native-community` is deprecated , please don't use it.

[Please refer to installation docs](https://react-native-async-storage.github.io/async-storage/docs/install)

**Comment by haveamission** [comment] 2021-11-28 03:57
Still having this issue on Expo SDK 43

**Comment by liyamahendra** [comment] 2022-11-09 12:14
Running into this issue.

I'm using: 

- React native 0.62.2 (is an old project) 
- @react-native-async-storage/async-storage 1.17.10

Facing this issue on Android.

@krizzu any suggestions please?

![image](https://user-images.githubusercontent.com/911879/200827410-ceec2a47-cff2-44cb-ab99-18c0b6763fe0.png)

**Comment by krizzu** [comment] 2022-11-09 12:24
Please provide exact error you see + sample code, so I could investigate

**Comment by liyamahendra** [comment] 2022-11-09 13:28
@krizzu My project was using `AsyncStorage` from `react-native`; I just installed `react-native-async-storage/async-storage` as a part of the incremental upgrade and ran into this error. So apparently, there is no specific code to reproduce this.

The screenshot shows the exact error and stack trace please. 

Happy to share any more details you may need and I can provide.

**Comment by krizzu** [comment] 2022-11-11 17:57
If you can provide a repo that can reproduce the error, I'll be able to help.
Make sure that after you install the package to re install your app

**Comment by liyamahendra** [comment] 2022-11-20 18:57
I noticed the below error in my project console:

```
console.error: React Native version mismatch.

JavaScript version: 0.62.3
Native version: 0.71.0-rc.0
```

Resolved this issue by fixing the version mismatch.
