### ISSUE TITLE
SyntaxError: Unexpected token export using jest

### ISSUE THREAD

**Issue by loic-lopez** [react-native-community/react-native-async-storage#39] opened 2019-03-14 20:03 UTC
## Current behavior

```bash
/@react-native-community/async-storage/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export default from './AsyncStorage';

 SyntaxError: Unexpected token export

    > 1 | import AsyncStorage  from "@react-native-community/async-storage"
        | ^
      2 | 
      3 | /**
      4 |  * Loads a string from storage.

```

## Repro steps

`import @react-native-community/async-storage` and test with jest.

## Environment

- **Async Storage version**: 1.2.1
- **React-Native version**: 0.57.7
- **Platform tested**: iOS / Android
- **Jest version**: 24.0.11
- **Logs/Error that are relevant**: see above

**Comment by Krizzu** [comment] 2019-03-15 08:14
Hey @loic-lopez 

Async Storage is not being transformed by Jest, so in your `jest.config.js` or `jest` entry in `package.json`, add:

```
"transformIgnorePatterns": ["/node_modules/@react-native-community/async-storage/(?!(lib))"]
```

**Comment by vgm8** [comment] 2019-03-15 13:36
The error still happening after adding your solution.

**Comment by loic-lopez** [comment] 2019-03-15 15:33
@Krizzu thanks for reply and yes `transformIgnorePatterns` seems to have solved the problem but,
when i try to mock the library like that:
<img width="508" alt="Capture d’écran 2019-03-15 à 11 30 54" src="https://user-images.githubusercontent.com/17724398/54442869-d8481a00-4715-11e9-9282-bbf42b52ad8a.png">

**I got:** 
```bash
● save

    expect(jest.fn()).toHaveBeenCalledWith(expected)

    Expected mock function to have been called with:
      ["something", "{\"x\":1}"]
    But it was not called.

      34 | test("save", async () => {
      35 |   await save("something", VALUE_OBJECT)
    > 36 |   expect(mockSetItem).toHaveBeenCalledWith("something", VALUE_STRING)
         |                       ^
      37 | })
      38 | 
      39 | test("saveString", async () => {

      at Object.<anonymous>.test (test/tests/storage.test.ts:36:23)
```

**as if the mock did not work**

**Comment by Krizzu** [comment] 2019-03-15 15:49
@loic-lopez This is more like Jest question :) You can checkout [Jest docs about mocking node_modules libs](https://jestjs.io/docs/en/manual-mocks#mocking-node-modules).

Basically, create `__mocks__` in project root (unless your `roots` Jest settings says differently), create `@react-native-community/async-storage/index.js` in there and export mocked functions.


@vgm8 Anything particular that could help me figuring this out?

**Comment by loic-lopez** [comment] 2019-03-15 16:03
@Krizzu the mock is on top of my `@react-native-community/async-storage` test see bellow:
<img width="640" alt="Capture d’écran 2019-03-15 à 12 03 40" src="https://user-images.githubusercontent.com/17724398/54445049-63c3aa00-471a-11e9-8f96-ea070d1c18cf.png">

**Comment by vgm8** [comment] 2019-03-17 20:15
@loic-lopez your solution was not working because i had some errors in the jest configuration. After I fixed it works fine, thank you!

**Comment by Krizzu** [comment] 2019-03-19 08:54
@vgm8 	Thanks great!

Would you mind sharing your solution, for future references?

**Comment by loic-lopez** [comment] 2019-03-19 11:40
@Krizzu As you can see above, the mock is being running before my tests.

**Comment by NemanjaManot** [comment] 2019-03-20 14:28
I have same issue. @loic-lopez

**Comment by vgm8** [comment] 2019-03-20 15:11
Sure @Krizzu! As you said in your comment I've created `__mocks__/@react-native-community/async-storage/index.js`

```
let cache = {};
export default {
  setItem: (key, value) => {
    return new Promise((resolve, reject) => {
      return (typeof key !== 'string' || typeof value !== 'string')
        ? reject(new Error('key and value must be string'))
        : resolve(cache[key] = value);
    });
  },
  getItem: (key, value) => {
    return new Promise((resolve) => {
      return cache.hasOwnProperty(key)
        ? resolve(cache[key])
        : resolve(null);
    });
  },
  removeItem: (key) => {
    return new Promise((resolve, reject) => {
      return cache.hasOwnProperty(key)
        ? resolve(delete cache[key])
        : reject('No such key!');
    });
  },
  clear: (key) => {
    return new Promise((resolve, reject) => resolve(cache = {}));
  },

  getAllKeys: (key) => {
    return new Promise((resolve, reject) => resolve(Object.keys(cache)));
  },
}
```

An then in my tests I just import and mock `@react-native-community/async-storage` like this:

```
import AsyncStorage from '@react-native-community/async-storage';
jest.mock('@react-native-community/async-storage');
```

**Comment by loic-lopez** [comment] 2019-03-22 18:02
@NemanjaManot Do you have resolved your issue?

**Comment by NemanjaManot** [comment] 2019-03-25 08:12
@loic-lopez  not yet.

**Comment by opiruyan** [comment] 2019-03-27 11:33
getting
`@RNCommunity/AsyncStorage: NativeModule.RCTAsyncStorage is null.`
after adding `transformIgnorePatterns`

**Comment by Krizzu** [comment] 2019-03-27 19:25
@opiruyan 	Thanks!

This is from latest release (1.2.2), where we notice devs to link the library in order to use it.

I'll try to come up with custom mocks + docs to help people test this library on the weekend.

thanks.

**Comment by tsvetan-ganev** [comment] 2019-03-29 12:10
@vgm8, thanks for your mock implementation, it saved me time and I can confirm that it works.

**Comment by Krizzu** [comment] 2019-04-01 16:47
Hey everyone participating in this issue,

I've created a PR with [mocks and jest integration guide](#53), so I hope future issues with testing would be resolved.

Let me know what you think!

thanks.

**Comment by loic-lopez** [comment] 2019-04-01 21:16
@Krizzu thanks but your link seems to be broken.

**Comment by nirre7** [comment] 2019-04-08 08:57
@Krizzu 

Updated the lib but I din't get the @react-native-community/async-storage/**jest/async-storage-mock**

The jest folder doesn't seem to be included in the dist of react-native-async-storage?

**Comment by Krizzu** [comment] 2019-04-08 10:01
@nirre7,

`Jest` mocking is not yet releases, going to do it after merging #61 and #57 later today.

**Comment by opiruyan** [comment] 2019-04-09 09:50
looks like RN took care of **transformIgnorePatters**-part of the issue
https://github.com/facebook/react-native/releases/tag/v0.59.4

**Comment by Krizzu** [comment] 2019-04-09 10:25
@opiruyan Correct, should adjust docs to mention `0.59.4` instead of `0.60`
https://github.com/react-native-community/react-native-async-storage/blob/master/docs/Jest-integration.md#syntaxerror-unexpected-token-export-in-async-storagelibindexjs

**Comment by Krizzu** [comment] 2019-04-11 05:31
Released in v1.3.0, please check it out 🙏

**Closed by Krizzu** 2019-04-11 05:31 UTC
Labels: Bug

**Comment by JBaczuk** [comment] 2019-05-29 21:16
I set it up according to the docs, and I'm getting

```
node_modules/@react-native-community/async-storage/jest/async-storage-mock.js:6
    type KeysType = Array<string>;
         ^^^^^^^^

    SyntaxError: Unexpected identifier
```

**Comment by redreceipt** [comment] 2019-07-21 19:17
@Krizzu I'm still have issues, are you aware of this problem:

```
 FAIL  src/slides/AskNotifications/AskNotificationsConnected.tests.js
  ● Test suite failed to run

    .../node_modules/@react-native-community/async-storage/jest/async-storage-mock.js:6
    type KeysType = Array<string>;
         ^^^^^^^^

    SyntaxError: Unexpected identifier
```

The [solution here](https://stackoverflow.com/questions/56245766/mocking-react-native-async-storage-on-jest#) was switching to a different mocking package but I'm hoping that's not necessary.

**Comment by redreceipt** [comment] 2019-07-21 19:24
> @Krizzu I'm still have issues, are you aware of this problem:
> 
> ```
>  FAIL  src/slides/AskNotifications/AskNotificationsConnected.tests.js
>   ● Test suite failed to run
> 
>     .../node_modules/@react-native-community/async-storage/jest/async-storage-mock.js:6
>     type KeysType = Array<string>;
>          ^^^^^^^^
> 
>     SyntaxError: Unexpected identifier
> ```
> 
> The [solution here](https://stackoverflow.com/questions/56245766/mocking-react-native-async-storage-on-jest#) was switching to a different mocking package but I'm hoping that's not necessary.

turns out I fixed it by using @vgm8's mock [above](https://github.com/react-native-community/async-storage/issues/39#issuecomment-474875949) So maybe there's a syntax error in the official one that Jest doesn't like.

**Comment by janpe** [comment] 2019-08-29 13:17
@Krizzu should the problem mentioned above be fixed in the official mock? I'm getting the same thing.

**Comment by Krizzu** [comment] 2019-08-30 05:57
@redreceipt 	@janpe 	We use this setup on the repo's example app and it's fine. Seems like your setup might be missing a proper flow handling.
What's the preset you use? How does your setup look like? Could you come up with a repo that I could look into?

**Comment by frozenzia** [comment] 2019-09-17 07:06
We see the same `KeysType` error. Also fixable by using @vgm8's mock.

**Comment by Krizzu** [comment] 2019-09-17 07:13
It seems like the issue comes from the lack of transformation by Jest. [We have a docs on how to fix this here](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Jest-integration.md#syntaxerror-unexpected-token-export-in-async-storagelibindexjs). Let me know if it worked.

**Comment by frozenzia** [comment] 2019-09-17 09:26
@Krizzu, no help, at least, with the "Jest setup file" option.

**Comment by cinder92** [comment] 2019-09-24 03:49
@frozenzia did you find the solution for this? im having the same...

**Comment by frozenzia** [comment] 2019-09-24 07:05
@cinder92 , no, actually. I got fed up / out-of-time trying to figure out what was going on with the mock included in the package, and just went with a modified version of @vgm8's mock. We only needed setItem, getItem, and removeItem, AND we have some airBnB eslint rules in place so that the end result was that __mocks__/@react-native-community/async-storage.js (note name! opted for this instead of making an additional async-storage folder and putting index.js in it) looks like this:
```
const cache = {};
export default {
    setItem: (key, value) => new Promise((resolve, reject) => {
        const retVal = (typeof key !== 'string' || typeof value !== 'string')
            ? reject(new Error('key and value must be string'))
            : resolve(cache[key] = value);
        return retVal;
    }),
    getItem: key => new Promise(resolve => (
        Object.prototype.hasOwnProperty.call(cache, key)
            ? resolve(cache[key])
            : resolve(null))),
    removeItem: key => new Promise((resolve, reject) => (
        Object.prototype.hasOwnProperty.call(cache, key)
            ? resolve(delete cache[key])
            : reject(new Error('No such key!')))),
};
```

**Comment by Krizzu** [comment] 2019-09-24 08:16
@frozenzia How does your setup looks like? Is it monorepo by any chance?

>  
    type KeysType = Array<string>;
         ^^^^^^^^

    SyntaxError: Unexpected identifier

Looks like an issue with `Flow` type striping. Do you have it included in your project?

**Comment by janhesters** [comment] 2019-11-05 08:24
My project neither contains Flow nor TypeScript and I too get the `KeysType` error:

```bash
  ● Test suite failed to runmponent.test.js

    /Users/jan/dev/my-app/node_modules/@react-native-communit
y/async-storage/jest/async-storage-mock.js:
6
    type KeysType = Array<string>;
         ^^^^^^^^

    SyntaxError: Unexpected identifier
```

**Comment by jsidorenko** [comment] 2019-11-13 15:37
It's also possible to exclude this file in .flowconfig by adding `<PROJECT_ROOT>/node_modules/@react-native-community/async-storage/jest/.*` under the `[ignore]` section

**Comment by fabiendem** [comment] 2019-11-28 16:44
I have fixed the error
```
type KeysType = Array<string>;
         ^^^^^^^^

    SyntaxError: Unexpected identifier
```
using those instructions in my project: https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Jest-integration.md#syntaxerror-unexpected-token-export-in-async-storagelibindexjs

**Comment by belgamo** [comment] 2020-04-23 05:01
> I have fixed the error
> 
> ```
> type KeysType = Array<string>;
>          ^^^^^^^^
> 
>     SyntaxError: Unexpected identifier
> ```
> 
> using those instructions in my project: https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Jest-integration.md#syntaxerror-unexpected-token-export-in-async-storagelibindexjs

https://github.com/react-native-community/async-storage/issues/194#issuecomment-562094202
